import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { auth } from '@/auth';
import { Providers } from '@/components/custom/Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Ethereum Dashboard',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // get server session
  const session = await auth()

  return (
    <html lang="en">
      <body
        className={`${inter.className} ${inter.className} antialiased flex flex-row w-full h-full min-h-screen`}
      >
        <Providers session={session}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
