# Generated by Django 5.1.4 on 2024-12-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EthereumBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_hash', models.CharField(max_length=66, unique=True)),
                ('block_number', models.BigIntegerField(unique=True)),
                ('difficulty', models.BigIntegerField(blank=True, null=True)),
                ('gas_limit', models.BigIntegerField(blank=True, null=True)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('miner', models.CharField(blank=True, max_length=42, null=True)),
                ('parent_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('timestamp', models.DateTimeField()),
                ('transactions', models.JSONField(blank=True, null=True)),
                ('transaction_count', models.IntegerField()),
                ('total_difficulty', models.BigIntegerField(blank=True, null=True)),
                ('uncles', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-block_number'],
            },
        ),
    ]
