# Generated by Django 5.1.4 on 2024-12-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethapp', '0002_remove_ethereumblock_total_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ethereumblock',
            name='transactions',
        ),
    ]
