# Generated by Django 5.1.4 on 2024-12-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethapp', '0003_remove_ethereumblock_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethereumblock',
            name='block_hash',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='ethereumblock',
            name='parent_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
