# Generated by Django 5.1.4 on 2024-12-12 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethapp', '0004_alter_ethereumblock_block_hash_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ethereumblock',
            options={'ordering': ['block_number']},
        ),
    ]
