# Generated by Django 5.1.4 on 2024-12-14 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethapp', '0005_alter_ethereumblock_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ethereumblock',
            options={'ordering': ['-block_number']},
        ),
    ]
