# Generated by Django 5.1.4 on 2024-12-15 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethapp', '0006_alter_ethereumblock_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ethereumblock',
            name='difficulty',
        ),
    ]
