# Generated by Django 5.1.4 on 2024-12-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethapp', '0007_remove_ethereumblock_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinbaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('base_currency', models.CharField(max_length=10)),
                ('quote_currency', models.CharField(max_length=10)),
                ('base_increment', models.DecimalField(decimal_places=10, max_digits=20)),
                ('quote_increment', models.DecimalField(decimal_places=10, max_digits=20)),
                ('display_name', models.CharField(max_length=100)),
                ('min_market_funds', models.DecimalField(decimal_places=10, max_digits=20)),
                ('margin_enabled', models.BooleanField()),
                ('post_only', models.BooleanField()),
                ('limit_only', models.BooleanField()),
                ('cancel_only', models.BooleanField()),
                ('status', models.CharField(max_length=20)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('auction_mode', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EthereumTicker',
            fields=[
                ('trade_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('size', models.DecimalField(decimal_places=10, max_digits=20)),
                ('time', models.DateTimeField()),
                ('bid', models.DecimalField(decimal_places=10, max_digits=20)),
                ('ask', models.DecimalField(decimal_places=10, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=10, max_digits=20)),
                ('rfq_volume', models.DecimalField(blank=True, decimal_places=10, max_digits=20)),
                ('conversions_volume', models.DecimalField(blank=True, decimal_places=10, max_digits=20)),
            ],
        ),
    ]
