# Generated by Django 5.1.4 on 2024-12-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethapp', '0008_coinbaseproduct_ethereumticker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinbaseProduct',
        ),
        migrations.DeleteModel(
            name='EthereumTicker',
        ),
    ]
