# Generated by Django 5.1.4 on 2024-12-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinbaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('base_currency', models.CharField(max_length=10)),
                ('quote_currency', models.CharField(max_length=10)),
                ('base_increment', models.DecimalField(decimal_places=10, max_digits=20)),
                ('quote_increment', models.DecimalField(decimal_places=10, max_digits=20)),
                ('display_name', models.CharField(max_length=100)),
                ('post_only', models.BooleanField()),
                ('limit_only', models.BooleanField()),
                ('cancel_only', models.BooleanField()),
                ('status', models.CharField(max_length=20)),
                ('auction_mode', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('product_id', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('volume_24_h', models.DecimalField(decimal_places=10, max_digits=20)),
                ('low_24_h', models.DecimalField(decimal_places=10, max_digits=20)),
                ('high_24_h', models.DecimalField(decimal_places=10, max_digits=20)),
                ('low_52_w', models.DecimalField(decimal_places=10, max_digits=20)),
                ('high_52_w', models.DecimalField(decimal_places=10, max_digits=20)),
                ('price_percent_chg_24_h', models.DecimalField(decimal_places=16, max_digits=20)),
                ('best_bid', models.DecimalField(decimal_places=10, max_digits=20)),
                ('best_ask', models.DecimalField(decimal_places=10, max_digits=20)),
                ('best_bid_quantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('best_ask_quantity', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
